// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc5107.Chell.subsystems;
import org.usfirst.frc5107.Chell.RobotMap;
import org.usfirst.frc5107.Chell.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class DriveTrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    //SpeedController leftMotor = RobotMap.driveTrainLeftMotor;
    //SpeedController rightMotor = RobotMap.driveTrainRightMotor;
    RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    RobotDrive drive = new RobotDrive(RobotMap.driveTrainLeftMotor,RobotMap.driveTrainRightMotor);
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new DriveWithJoysticks());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    public void drive(Joystick leftJoy,Joystick rightJoy){

 
        robotDrive.tankDrive(leftJoy, rightJoy);

    }
    public void drive1(double leftValue,double rightValue){
        robotDrive.tankDrive(leftValue, rightValue);
        System.out.println("ITS FUCKING RUNNING");
    }
    public void stop(){
        robotDrive.drive(0, 0);
    }
}
